### ISSUE TITLE
SyntaxError: 'await' outside function

### ISSUE THREAD

**Issue by ssolson** [jcreek/discord.py-welcome-bot#6]
How would I set the await up inside of a function?

```
PS C:\Users\sterl\Codes\discord.py-welcome-bot> python .\welcome-bot.py
  File ".\welcome-bot.py", line 7
    welcomechannel = await client.fetch_channel(###myChannelNumber###)
                                  ^
SyntaxError: 'await' outside function
```

**Comment by jcreek** [comment]
Hi @ssolson, 

It appears you are trying to run this code using an incompatible version of Discord.py - this code requires version 0.16.12, as evidenced in the Dockerfile. 

Thanks for getting involved! 

jcreek
