### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by rursi** [jcreek/discord.py-welcome-bot#7]
File "role.py", line 38
    description="We're so glad you're here!"
    ^
SyntaxError: invalid syntax

**Comment by jcreek** [comment]
Hi @rursi , thanks for raising this. 

As stated on the readme, this project is no longer maintained and requires specific versions of both python and the discord.py library to work, specifically python 3.6.9 and discord.py 0.16.12 - with these installed this syntax is correct. 

As such I will be closing this issue. If you want a modernised version, there are a large number of forks available where people have made their own updated versions. 

All the best, 

jcreek
